### ISSUE TITLE
部品さんのTwitter画像がリンク切れを起こしているようです

### ISSUE THREAD

**Issue by ghost** [interaxion-podcast/interaxion-podcast.github.io#14]
交代磁性のお話をとてもおもしろく聞きました。

本題ですが、部品さんのTwitter画像がリンク切れを起こしているようです。

![Screenshot 2024-09-05 23 00 00](https://github.com/user-attachments/assets/54feacb4-e37f-461a-80f5-175bcfbf924d)

**Comment by pn11** [comment]
ありがとうございます！ 初めて issue でコメントを頂いて感激です！
こちらで修正しました。
https://github.com/interaxion-podcast/interaxion-podcast.github.io/commit/a4be95e463eb0c367343d3dcec73f68e26600118
